soolzzak/FE

src/api/auth.ts, src/pages/Home.tsx
=> Fix: 중복 코드 삭제

src/assets/svgs/DeleteBtn.jsx, src/components/Home/JoinRoomModal.tsx, src/components/login/LoginModal.tsx, tailwind.config.js
Change primary color
'#E0F5E6',
'#B6ECC4',
'#0BA332',
'#179638',
'#179638',
=> Style: change primary color

src/assets/svgs/Monitor.tsx, src/pages/StreamRoom.tsx
=> feat. Add mic, monitor state

src/api/axios.ts, src/pages/StreamRoom.tsx, src/shared/Router.tsx
feat: Add axios interceptors
fix: stream room guest profile fuction
=> feat: Add axios interceptors

src/api/auth.ts, src/api/axios.ts, src/assets/svgs/Checkbox.jsx, src/components/Header/AuthModal.tsx, src/components/StreamRoom/ConfigDropDown.tsx, src/components/StreamRoom/WaitingGuestRef.tsx, src/components/login/ChangePwdInput.tsx, src/components/signup/SignupInput.tsx, src/components/signup/SignupInputForm.tsx, src/hooks/useError.ts, src/hooks/useInput.ts, src/index.css, src/pages/Signup.tsx, src/pages/StreamRoom.tsx
Fix: stream room mic on/off 코드 수정
=> Fix: stream room mic on/off 코드 수정

src/api/axios.ts, src/assets/svgs/Exit.tsx, src/components/Header/AddRoomButton.tsx, src/components/Header/AuthModal.tsx, src/components/Header/SearchField.tsx, src/components/Home/CategoryTab.tsx, src/components/Home/ChatroomCard.tsx, src/components/Home/FilterPanel.tsx, src/components/Home/HeroSection.tsx, src/components/StreamRoom/CategoryDropDown.tsx, src/components/StreamRoom/ConfigDropDown.tsx, src/components/StreamRoom/LeaveRoomModal.tsx, src/components/StreamRoom/WaitingGuestRef.tsx, src/components/login/LoginModal.tsx, src/index.css, src/layout/Header.tsx, src/pages/KakaoCallBack.tsx, src/pages/StreamRoom.tsx
Style: main style 변경
Fix: axios interceptor header token 추가
=> Style: main style 변경

src/components/login/LoginModal.tsx, src/pages/StreamRoom.tsx, src/pages/StreamRoom2.tsx
=> Fix: kakao redirect uri 변경

src/pages/StreamRoom.tsx
=> Fix: import 변경

src/pages/KakaoCallBack.tsx, src/pages/StreamRoom.tsx
Fix: kakao usernameAtom 추가
Style: streamroom vh 삭제
=> Fix: kakao usernameAtom 추가

src/pages/StreamRoom.tsx
Fix: streamroom screenshare 코드 수정
=> Fix: streamroom screenshare 코드 수정

src/assets/svgs/NotFound.jsx, src/pages/NotFound.tsx, src/pages/StreamRoom.tsx, src/store/addRoomStore.ts
Fix: streamroom remote  mic muted 설정 변경
=> Fix: streamroom remote mic muted 설정 변경

src/api/streamRoom.ts, src/components/Home/JoinRoomModal.tsx, src/pages/StreamRoom.tsx
=> Fix: joinRoomModal 비밀번호 로직 수정

src/api/auth.ts, src/assets/svgs/NotFound.jsx, src/components/Home/JoinRoomModal.tsx, src/components/StreamRoom/ControlStreamRoom.tsx, src/components/login/LoginModal.tsx, src/components/signup/SignupInput.tsx, src/pages/StreamRoom.tsx, src/store/addRoomStore.ts, src/store/streamControlStore.tsx
Refactor: stream room component 분리
=> Refactor: stream room component 분리

src/api/streamRoom.ts, src/components/Home/CategoryTab.tsx, src/pages/StreamRoom.tsx, yarn.lock
=> Fix: 스트림룸 오류 코드 삭제

src/assets/svgs/Like.tsx, src/assets/svgs/UnLike.tsx, src/components/login/ChangePwdInput.tsx, src/components/signup/SignupInput.tsx, src/pages/StreamRoom.tsx
Style: stream room activity icon 배치 변경
=> Style: stream room activity icon 배치 변경

README.md
=> Feat: ReadMe

public/index.html
=> feat. og tag image 추가

src/pages/StreamRoom.tsx
[Style: streamroom video height 수정](https://github.com/soolzzak/FE/commit/d4bacf1d763857b6d84737d02450eab5c9b6b599)
=> Style: streamroom video height 수정

src/components/Home/JoinRoomModal.tsx, src/pages/StreamRoom.tsx
=> Stlye: stream css 수정

public/index.html, src/components/Home/JoinRoomModal.tsx
=> Docs: og 이미지 url 변경

src/api/auth.ts, src/api/mypage.ts, src/components/Header/NotificaionToggle.tsx, src/components/Mypage/DetailDropdown.tsx, src/components/Mypage/HistoryCard.tsx, src/components/Mypage/MessageModal.tsx, src/components/Mypage/MyinfoSection.tsx, src/components/Mypage/TabSection.tsx, src/components/StreamRoom/ControlStreamRoom.tsx, src/components/login/DeleteAccountModal.tsx, src/index.css, src/pages/Mypage.tsx, src/store/messageStore.tsx, src/store/modalStore.ts
Feat: messagemodal success toast 추가
=> Feat: messagemodal open 시 user로 연결 

src/components/StreamRoom/ControlStreamRoom.tsx
=> Fix: 화면 공유 text 변경

src/components/Header/NotificaionToggle.tsx, src/components/Header/ProfileMenu.tsx, src/components/Mypage/DetailDropdown.tsx, src/components/Mypage/MessageModal.tsx, src/components/common/Modal.tsx, src/store/mainpageStore.ts, src/store/messageStore.tsx
Fix: message modal header로 변경
Fix: 답장하기 버튼 클릭 시 username 초기화
=> Fix: message modal header로 변경
